### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by sbliven** [yutake27/P3CMQA#2]
The installation procedure for P3CMQA is pretty complex. It would be nice to have a Dockerfile, Vagrantfile, or similar to make installing more reproducible.

**Comment by yutake27** [comment]
Thank you for your suggestion. I also thought it was complex to install. I will try to create Dockerfile.

**Comment by yutake27** [comment]
@sbliven 
I've added a Dockerfile and published the Docker image on docker hub. Also, the usage with Docker has been added to the README.
